---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Arrays


In python Arrays are called lists. Arrays are contiguous memory data structure, which means each item is placed next to each other in memory. When accessing the array, an index is used which refers to the target memory as: `index 0 address` $+$ `size of item type` $\times$ `index`.  
This allows the arrays methods to jump to the target items without having to consider all the items in the array. This leads to the access of items in arrays to be a constant time $O(1)$ operation.  

```{python}
new_list = [1,2,3]
new_list[0]
```

Arrays must enforce the contigous memory allocation, infact you can only add new items to an array using the `.append` method [[nkmk-lists](https://note.nkmk.me/en/python-list-append-extend-insert)].

```{python}
new_list.append(4)
new_list
```

The `size of item type` indicates that arrays requires the items to have predetermined size. In fact languages such as C, Swift and Java only allow the arrays to be of a single type. This is referred to as hemongenous arrays. Python allows for heterogeneous arrays which means mixed data types can be stored in an array. But since, different data types can have different allocated sizes, and none of it predetermined, Python pointers of those items instead. So a Python array access method will do something like this: `index 0 address` + `size of pointer type` + `index`.

```{python}
new_list.append("imma-a-string")
new_list
```

So when ask the array to point to an index, the method will form the memory address and get the item in that address. But since that those bytes of memory are not part of the array type, it fails to read them.

```{python}
# new_list[5] ## index out of range
```

#### Operations on the Array

So far adding, intialising and retrieving items from an array has been shown. Let's try searching an array, which the demo will show is a far more expensive operation to perform, particularly in Python due to its pointers.

The following shows the use of the `in` operator to check if `new_list` contains 1. It calls a `contains` method which performs a linear search through the array to true if the item value exists. Even the acess and read operations are constant time, they still need to be performed as they there are items in the array, leading to a linear runtime $O(n)$.

```{python}
1 in new_list
```

__Inserting Items in an Array__  
True insert involves adding an item to a specified in an array, causing the rest of the items on the right to shift an index of + 1. This there for a linear runtime operation when considering adding a new value at index 0.


__Appending Items in an Array__  
This is a special case of insert, where the new item is added at end of an array, i.e. `array[len(array)] = "new_item"`. This is a constant time operation as jumping to the end of array is constant time and so it adding an item. There is no overhead of considering the rest of the items in an array.  
One caveat is that append's runtime complexity can be different for other languages because of its implementation.


When defining an empty list, Python allocates a 1 items array in memory. But inspite of that, when calling its length, it return 0. Indicating that Python is considering more than the memory allocation of the list to determine the length.

```{python}
numbers = []
len(numbers)
```

Lets append an item:

```{python}
numbers.append(2)
len(numbers)
```

Now the length of the array and the size in memory match. Now when appending another item, python must call a list resizing operation in order to increase the memory allocation of the list. There is a lot of ingenuity in its implementation.

```{python}
numbers.append(200)
```

When adding an item on index 1, Python resizes the list to have a memory of allocation of 4 items. This means Python does not need to perform a resizing operation each time a new item is inserted, only at specific points. Those specific points are at index: 0, 4, 8, 16, 25, 35, 46...

It may be argued that this means that appending an items is a non-consant space complexity. But it turns out that if you average the increases in space, it has a [constant ammortized](https://stackoverflow.com/questions/200384/constant-amortized-time) space complexity. That is on, average with no concern about the best and worse case, you'll generally have a constant space operation. With the memory allocation resizing it is easy to see why. More and more allocation is performed, and given the additions do not match that rate, less resizing will be required as the list grows.

This is true for the insert operation too, which may have a time complexity of $O(n)$ but an ammortised space complexity of $O(1)$.


__Extend Operation__  
Languages generally offer a means to join two arrays together. In Python is done with the `.extend([])` operation.

```{python}
numbers = []
numbers.extend([4, 5, 6])
numbers
```

The extend method effective makes a series of append calls to the other elements which has k items. This means this operation has a big O of $O(k)$.


__Delete Operation__  
When you delete an item at an index, the method for delete needs to remove that item and reenforce the contigious index. So in an opposing fashion to append and insert, items to the right of the delete items are shifted to by an index of -1. In addition, resizing is also handled, similar to append and insert operations.  
Given what we know from earlier, this means that operation has a time complexity of $O(n)$.

```{python}
del numbers[0]
numbers
```

You also have a `.remove(item)` operation which searches and then deletes the item with `del`. Since searching is $O(n)$ and `del` is $O(n)$, this is a $O(n)$ runtime operation with a $O(1)$ space complexity [[codebot-list-remove](https://thecodingbot.com/pythons-list-remove-time-and-space-complexity-analysis/)].

```{python}
numbers.remove(5)
numbers
```

#### Questions


`[?]` Why are Python Lists treated as Arrays?  
`[>]` Python's List implementation is really a [dynamic array](https://en.wikipedia.org/wiki/Dynamic_array) and is unlike the Lisp-style linked list you would initally think [[Py-Docs-DH](https://docs.python.org/3/faq/design.html#how-are-lists-implemented-in-cpython)]. By carrying a continguous list of pointers instead of a linked list means indexing the list is less costly. It common for programming languages to use [associative arrays](https://en.wikipedia.org/wiki/Associative_array) which just arrays that hold a `key,value` pair. They are meant to behave like lists but otherwise remain efficient for practical applications [[wiki-arr-imp](https://en.wikipedia.org/wiki/List_(abstract_data_type)#Implementations)].


`[?]` What makes Arrays so good for reading items?  
`[>]` Arrays list contiguously (sequentially) in a memory so all you need to know is where the first item of the array first via a `head`, the data type and an index. The data type defines the size of the item and can jump straight to the desired item like so: `item_address` $=$ `head` $+$ `data_type_size` $\times$ `index`.


`[?]` From a Data Structures point of view are Lists, linked lists?  
`[>]` In theory that is what they are but in programming language the implementation can lead this to vary wildly. The list data type may be behave like a linked list but will not have any of the baggage that theoretically linked list should have. For example, Python uses a dynamic array of pointers, which makes reading super quick and support a list of mixed data types.


`[?]` Is Python's implementation of Arrays pretty much as linked list?  
`[>]` No, Python runs as far as it can from a linked list. Python's array data structure is a proper array which is restriction to its `list` data type. You need to import the `array` module and define the data type to be used at initialisation [[py-doc-arr](https://docs.python.org/3/library/array.html?highlight=array#module-array)]. Generally you just use Lists [[so-arr-str](https://stackoverflow.com/questions/57301478/how-to-create-an-array-of-strings-by-using-array-module)]. [[gh-cpy-listobj](https://github.com/python/cpython/blob/5c22476c01622f11b7745ee693f8b296a9d6a761/Objects/listobject.c#L22)] show what the implementation looks like.


`[?]` From a Data Structures Point of View, what operations should an Array offer?  
`[?]` From a Data Structures Point of View, how are operations of a linked list different from an array?  
`[?]` What operations does Python offer on its `Array` implementation?  
`[?]` Do you know what the Big O is for the Array implementation in Python?  
`[a]` Because, inserting and deleting a items in the array is costly and generally not what arrays are for. They are great for reading.  
`[?]` What is an ammortised constant complexity?  
`[?]` Why does the `.append` operation have a ammortized constant space complexity in Python?  
