---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

### Binary Search

Binary Search takes a list sorted in ascending order and a target value. Taking the Upper and Lower index bounds (e.g. len(list)-1 and 0) and finds floored midpoint index. It checks that midpoint position value from the list with the target value. If the midpoint value is too large, the Upper bound is set as the midpoint - 1 and if too small, the Lower bound is set as midpoint + 1. 

The search stops until the list(midpoint) == target or the lower bound is no longer Lower <= Upper

```{python}
def bin_search(list, target):
    lower = 0
    upper = len(list)-1
    
    while lower <= upper:
        midpoint = (lower + upper)//2
        print(lower, upper, midpoint, target)
        
        if list[midpoint] == target:
            return midpoint
        elif list[midpoint] > target:
            upper = midpoint - 1
        else:
            lower = midpoint + 1
            
    return None
```

```{python}
listA = [x for x in range(5,10)]
```

```{python}
pos = bin_search(listA, 2)
```

```{python}
pos
```

I wonder if there is a recursive version of this.

```{python}
def eval_mid(lower, upper, list, target):

    midpoint = (lower + upper)//2

    print(lower, upper, midpoint, list[midpoint], target)
    
    if lower > upper:
        return None

    elif list[midpoint] == target:
        return midpoint

    elif list[midpoint] > target:
        upper = midpoint - 1
        return eval_mid(lower, upper, list, target)

    elif list[midpoint] < target:
        lower = midpoint + 1
        return eval_mid(lower, upper, list, target)



def rec_bin_search(list, target):
    
    lower = 0
    upper = len(list)-1
    print("L", "U", "M", "C", "T") ## C for current value at midpoint
    pos = eval_mid(lower, upper, list, target)
    return pos
    
```

```{python}
pos = rec_bin_search(listA, 5)
```

One of the big assumptions is that the list must be sorted in ascending order.   
`[ ]` Is there way to check that without running a full sort algorithm? 


The version of recursion resizes the original list and calls the function again. What is lost are the upper and lower bounds relative to the original list, but otherwise it appears neater.

```{python}
def rec2_bin_search(list, target, debug=False):

    midpoint = (0 + len(list)-1)//2
    
    if debug == True:
        print(list)

    if 0 > midpoint:
        if debug == True:
            print('None')
        return None    
    
    elif list[midpoint] == target:
        if debug == True:
            print(f'[{list[midpoint]}]') 
        return midpoint

    elif list[midpoint] > target:
        return rec2_bin_search(list[:midpoint], target, debug)

    elif list[midpoint] < target:
        return rec2_bin_search(list[midpoint+1:], target, debug)
```

_notes_  
syntax sugar: `midpoint+1:` instead of `midpoint+1:len(list)-1`  
syntax sugar: `:midpoint` instead of `:midpoint`

```{python}
pos = rec2_bin_search(listA, 100, debug=True)
```

__Why does this code work?__
Disabling the `0 > midpoint` check at line 8 leads to the following statements to evaluate an empty list leading to an index error:

line 19: `return rec2_bin_search(list[:midpoint], target, debug)`  
line 20: `return rec2_bin_search(list[midpoint+1:], target, debug)` 

When line 8 is enabled, before the evaluation of these statements the list is empty, which line 8 detects and returns `None` for.


`[ ]` Is a function call expensive?  
`[ ]` Is there a cost to making binary search resursive?


__Why use recursion over a while loops?__
The recursive version helps highlight the logarithmic aspect of the function as the function clearly calls itself with a list half the size until there nothing left.  
Another reason could be that unlike a while loop, you are managing the space taken by the evaluation through its call stack. When the recursion yields, each call returns a value and the rest of the function is discarded.  
Older textbooks and works that were usually written by mathematicians tended to write their program using the functional paradigm. This resulted in them favouring the recursive format.  
Python does not however optimise recursion well. In fact python has a maximum recursion depth of up to 999 [as explained in a StackOverflow Q&A](https://stackoverflow.com/questions/3323001/what-is-the-maximum-recursion-depth-in-python-and-how-to-increase-it). So for python an iterative implementation is preferred.  
However, a other languages, especially functional languages are fine or works better with the recursive version.

__Space Complexity considerations__  
The iterative version's space complexity constant, i.e. O(1). This is as the size of the algorithm for a given problem does not grow as it completes the task. This is in contrast to the recursive version.  
The recursive version create a new sub-list and calculates the midpoint, which means it grows during a problems execution. In fact, the larger the list the high number of calls to break that list down by 2, all the way to 1 item list. It follows the $log_2(n)$ format, making its Space Complexity to be $O(log_2(n))$.  
The caveat however is that this depends on the language as it may provide affordances where such a cost may not occur. This kind of optimisation is called [Tail Optimisation](https://stackoverflow.com/questions/310974/what-is-tail-call-optimization). Python does not implement tail call optimisation.


__TODO-extension__  
`[ ]` You forgot to return recursive statements, raise an issue and then fix it.  
`[ ]` Try out a list of strings instead?  
`[ ]` Can it work with lists of different types?  
`[ ]` Can you write a generic for binary search?  
`[ ]` Use gh issues to track gotcha's.  
`[ ]` Create a program that gets the problem and fix of each issue.  
`[ ]` Find out if C++ and JavaScript have any recursion limits.  
`[ ]` Find out what tail optimisation is and its use in various languages.  
`[ ]` Find out a way to measure the time and space taken by an algorithm.

```{python}
def rec3_bin_search(list, value):
    
    mid = (len(list) -1) // 2
    print(len(list))
    
    if len(list) - 1 == 0:
        return False

    elif list[mid] == value:
        return True

    elif list[mid] > value:
        L = list[:mid]
        return rec3_bin_search(L, value)

    elif list[mid] < value:
        R = list[mid + 1:]
        return rec3_bin_search(R, value)

    return False
```

```{python}
a = [1, 3, 5]

rec3_bin_search(a, 2)
```

```{python}
(len(a) - 1) // 2
```

`[?]` Explain how `rec3_bin_search` and `rec2_bin_search` are different and why? Are they really equivalent?  
`[?]` Most of these Binary Search recursive algorithm don't know the position of the found value in relation to the original array. Can you modify any of the recursive binary search algorithms to track that?
