---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Linked List

#### Why build your own data structures?
Sometimes the data structures a programming language provides are too costly from a time and space complexity perspective for your usage profile. For example, Arrays are great to reading and retrieving values ($O(1)$) but are slower when inserting and deleting items ($O(n)$). If you have a case where you do a lot inserting and deleting, a linked list is slightly better.

`[ ]` Find more reasons why building your own data structures can be better

#### An appreciation of data structures underlying existing code bases
Most of the time you won't have build any data structures. However, the principles that underpin their performance and the affordances they provides need to be understood in practical contexts. By grappling with various Data Structures and Algorithms you can more critical in choosing the right data types, libraries and functions.

#### What is a linked list?

It is a linear data structure where each item is a node which carries a value and a pointer to the next node. The first node of the list is known as the head and the last node as the tail. Most implementations only know the location of the head of the list, some also keep track of the tail. Node are known as self-referential objects as each node points to another node and the definition of the node refers to itself.  
There are two kinds of linked lists: singly linked list, where each node has one pointer to the next node, and a doubly linked list, where each node has two pointers the extra one referring to the previous node. With a doubly linked list, you can move up and down the linked list, you can't do that with a singly linked list.


Define the basic node object:

```{python}
class Node:
    """
    An object for storing a single node of a linked list.
    Models two attributes - data and the link to the next node in the list
    """
    data = None
    next_node = None
    
    def __init__(self, data):
        self.data = data
        
        
    def __repr__(self):
#         return "<Node data: %s %s>" % self.data % self.next_node
        return f"<Node data: {self.data}>"
```

Define the LinkedList class that uses the node object to create a linked list. Technical after a few essential function much of the functions are there for convenience and become increasingly favourable for specific scenarios instead of anything general. This will be discussed when talking about the Big O of each of the functions.

```{python}
class LinkedList:
    """
    Singly-linked list
    """
    
    def __init__(self):
        self.head = None
        
    def is_empty(self):
        """
        return True is self.head == None is true
        """
        return self.head == None
    
    def append(self, data):
        """
        Creates a new node with Data at the tail node
        This new node then becomes the Tail Node
        """
        
        if self.head == None:
            self.head = Node(data)
        else:
            current = self.head
            while current.next_node:
                current = current.next_node

            current.next_node = Node(data)
            
    def prepend(self, data, debug=False):
        """
        Creates a new head node with the target data
        ans sets the previous head to .next_node to current head
        """
        previous_head = self.head
        if debug==True: print(f"previous_head: \t {previous_head}")
        self.head = Node(data)
        if debug==True: print(f"new self.head: \t {self.head}")
        self.head.next_node = previous_head
        if debug==True: print(f"next_node: \t {self.head.next_node}")
                        
    def __repr__(self):
        return (f"<Linked List> \t{self.head} \ncount: {self.size()}")
    
    # convenience method
    def size(self):
        """ 
        Returns the number of nodes in the list
        Takes O(n) time
        """
        current = self.head
        count = 0
        
        while current: #!= None
            count = count + 1
            current = current.next_node
            
        return count
    
    # convenience method
    def to_array(self):
        """
        takes a LinkedList Object and constructs an 
        array of data attributes for each node
        """
        current = self.head
        array = []
        
        while current:
            array.append(current.data)
            current = current.next_node
            
        return array
    
    # convenience method
    def iget(self, index):
        """
        Takes the index number and returns 
        a node object that sits at that index.
        
        Throws an out of range error when index 
        is larger than the linked list.
        """
        current = self.head
        count = 0
        size = self.size()
        while count <= size-1:
            if count == index:
                return current
            elif current.next_node:
                current = current.next_node
            count += 1
                
        raise IndexError(f"Index out of Range\n{self}")
        
    def findi(self, data):
        """
        Take the data specified and find instances.
        Records their index and returns an array of
        index values of matching nodes.
        """
        
        current = self.head
        index = 0
        indexes = []
        
        while current:
            if current.data == data:
                indexes.append(index)
            index += 1
            current = current.next_node
            
        return indexes
    
    def exists(self, data):
        """
        Returns true or false if a given value exists in a linked list
        """
         
        finds = self.findi(data)
        return len(finds) > 0
    
    def insert(self, index, data):
        """
        Gets node at nth index and prepends that node with node with target data.
        """
        before_node = self.iget(index-1)
        insert_node = Node(data)
        insert_node.next_node = before_node.next_node
        before_node.next_node = insert_node
        
    def idelete(self, index):
        """
        Deletes node that is at ith index.
        
        Throws an index out of range error if 
        index does not exist in linked list.
        """
        
        if index != 0:
            before_node = self.iget(index-1)
            delete_node = before_node.next_node
            if delete_node.next_node == None:
                before_node.next_node = None
            else:
                after_node = delete_node.next_node
                before_node.next_node = after_node
            
        else:
            self.head = self.head.next_node
```

`[ ]` How do you substitute two variables in a string using `%`? fix `line 42`  
`[ ]` Why does the above code work, in spite of any explicit reasoning around pointers?  
`[ ]` This is most evident in `insert` and `idelete` methods. Why should `before_node` assignment change the original linked list? For all I know that I changed another instance of the node in memory, separate from the linked list.


__Convenience Methods__  

A convenience method is a method are affordances a data structure can provide that do not add functionality to the data structure per se, but instead give methods for the usual thing you would do. This ensures you don't have to recreate a method and assures you can focus on the code that specifically bring the functionality you're concerned with. It allows the author of the data structure to write the most efficient and convenient version.

In the `LinkedList` Class, I have provided `size` and `to_array` methods which one can implement themselves but why make 'em do it is common? That said, the more convenient methods can be considered to be opinionated to specific general scenario.

You need to be aware of how they behave. Specifically from a complexity standpoint, you need to decide if a custom implementation is required or some other library extension.

```{python}
N1 = Node(10)
# <__main__.Node at 0x7fe89449b760>    # Without __repr__
# <Node data: 10>                      # With __repr__
```

Without the `__repr__` dunder you get not-so-human friendly python jargon. Use `__repr__` to return something sensible and helpful.

```{python}
N2 = Node(20)
N1.next_node = N2
```

`[?]` At `line 2`, does the assignment to `next_node` involve passing the pointer to the object or the object itself?  
`[?]` When does the assignment operator give the object itself and when is the pointer around?

```{python}
L1 = LinkedList()
L1.append(10)
L1.append(20)
```

You can add loads of items with a range to the linked list! Lets give the .size() method a try.

```{python}
for x in range(1,10):
    L1.append(x)

L1.size()
# 11
```

Notice how when having brackets at end of `size` tells python it is method not a variable in the object. Much like you access `L1.head` to get data but `L1.head()` gives you uncallable type error.

```{python}
# L1.head()

# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# <ipython-input-109-ccb65b2c2cd9> in <module>
# ----> 1 L1.head()

# TypeError: 'Node' object is not callable
```

Lets try use the `.to_array` method.

```{python}
L1.to_array()
# [10, 20, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

The `.prepend` function in a linked list needs to parse all the way to the tail node. Of course I could create a feature that allows the tail node to be recorded and take advantage of that.  

`[ ] ` Create a `.tail` attribute which records the tail node.  
`[?] ` What impact does having the `.tail` attribute have to the rest of the functions?  
`[?] ` How does the Big O change for the function with / without the `.tail` attribute?

```{python}
L1.append(100)
# [10, 20, 1, 2, 3, 4, 5, 6, 7, 8, 9, 100]
```

The `.prepend` function simply swaps the `head` attritbute with a new node and ensure the old head is recorded to the new head's `.next_node` attribute. No shifting of indexes is required.

```{python}
L1.prepend(100) # debug=True

# previous_head: 	 <Node data: 10>
# new self.head: 	 <Node data: 100>
# next_node: 	 <Node data: 10>

# [100, 10, 20, 1, 2, 3, 4, 5, 6, 7, 8, 9, 100]
```

`[x]` Create an `.insert` method for the `LinkedList` class that takes an index and data to be added.

```{python}
L1.insert(4, 10)
# [100, 10, 20, 1, 10, 2, 3, 4, 5, 6, 7, 8, 9, 100]
L1.to_array()
```

`[v]` Modify the `.insert` method so that data is added _after_ a node with a given value.  
`[v]` Modify the `.insert` method give an option to add _before_ a node with a given value.  
`[ ]` Reason the Big O values for the `.append`, `.prepend` and `.insert` functions.  


`[x]` Create a `.delete` method to delete at `head`.  

```{python}
L1.idelete(0)
# [10, 20, 1, 10, 2, 3, 4, 5, 6, 7, 8, 9, 100]
L1.to_array()
```

`[x]` Create a `.delete` method to delete at `tail`.  

```{python}
L1.idelete(11)
# [10, 20, 1, 10, 2, 3, 4, 5, 6, 7, 8, 100]
L1.to_array()
```

`[x]` Create a `.delete` method to delete at an index(th) node.  

```{python}
L1.idelete(4)
# [10, 20, 1, 10, 3, 4, 5, 6, 7, 8, 100]
L1.to_array()
```

`[?]` How does Complexity of the `.delete` method compare with the array in python?  
`[?]` Given that Python Arrys uses pointers anyway, how large of a space-time complexity difference would you expectin languages like C, Swift or Java which don't do that?  

```{python}
# L1.idelete(100)
# index out of Range error from iget implemented within idelete
```

`[x]` Create a `.exists` method that checks if a node contains a specific `data` value.  

```{python}
L1.exists(100)
# True
```

```{python}
L1.exists(11)
# False
```

`[x]` Create a `.findi` method that returns the index of the node that contains the specified value in its `data` attribute.  

```{python}
L1.findi(10)
# [0,3]
```

```{python}
L1.findi(8)
# [9]
```

`[x]` Create a `.iget` method that returns the node object that sits at a given index.  

```{python}
#  0   1   2  3   4  5  6  7  8  9  10
# [10, 20, 1, 10, 3, 4, 5, 6, 7, 8, 100]

L1.iget(9)
#<Node data: 8>
```

```{python}
# L1.iget(13)
# Index out of Range
```

`[?]` How is Python's implementation of an Array better and worse compared to a standard concept of linked lists?  


### Linked List Implementation 2

```{python}
class LinkedList2:
    
    def __init__(self):
        self.head = None
        
    def __repr__(self):
        
        current = self.head
        arrList = []
        
        while current != None:
            arrList.append(current.data)
            current = current.next_node
       
        arrstring = ']->['.join([f'{node}' for node in arrList])
        return f"<LinkedList2> count:{len(arrList)} \n[{arrstring}]"
        
    def add(self,data):
        
        if self.head == None:
            self.head = Node(data)
        
        else:
            current = self.head
            
            while current.next_node != None:
                current = current.next_node
                
            current.next_node = Node(data)
        
```

```{python}
List2 = LinkedList2()
```

```{python}
List2.add(3)
List2.add(5)
List2.add(3)
List2
```

fix the buggy code below:

```{python}
class LinkedList2:
    
    def __init__(self):
        self.head = None
        
    def __repr__(self):
        
        current = self.head
        arrList = []
        
        while current != None:
            arrList = arrList.append(current.data)
            current = current.next_node
       
        arrstring = ']->['.join([f'{node}' in node for arrList])
        return len(arrList)
        
    def add(self,data):
        
        if self.head == None:
            self.head = Node(data)
        
        else:
            current = self.head
            
            while current != None:
                current = current.next_node
                
            current.next_node = Node(data)
```
