---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
def merge_sort (array):

    if len(array) == 1:
        return array

    elif len(array) > 1:
        midpoint = len(array) // 2
        s1 = merge_sort(array[:midpoint])
        s2 = merge_sort(array[midpoint:])
        
        for i in s1:
            index = 0
            for j in s2:
                if j >= i:
                    s2.insert(index, i)
                    break
                if index + 1 == len(s2):
                    s2.append(i)
                    break
                index += 1
        return s2
```

```{python}
arr = [2,3,1,66,0,9]
```

```{python}
merge_sort(arr2)
```

```{python}
arr = [6,3,4,5,6,6,6]
merge_sort(arr)
```

Compare with the merge sort implementation below and identify everything wrong with it.

```{python}
# def merge_sort_bad (array):

#     if len(array) == 1:
#         return array

#     elif len(array) > 1:
#         midpoint = len(array) // 2
#         s_1 = merge_sort(array[:midpoint])
#         s_2 = merge_sort(array[midpoint:])
#         while len(s2) > 0:
#             i = s2.pop()
#             index_j = 0
#             for j in s1:
#                 index_j += 1
#                 if j > i:
#                     s1.insert(index_j, s2)
#                 break

#     return s1
```

`index_j` incrementation should below line 17 as it should only be increment if current value is > or =.  

`if j > i:` does account for when `j == i` which is also a case where `i` should be inserted.  

`break` statement should be within `if` statement of line 16  

there is no case for when you are the end of the `s1` array because all values are less than the `i`, leading to missing values.  

`[?]` why would you want to implement a while loop instead of a for loop?  


`[?]` what key methods do you need from a data structure to enable easy implementation of merge sort?  


#### Neater Implementation of Merge Sort

```{python}
def merge_sort2(array):

    if len(array) == 1:
        return array

    else:

        mid = len(array) // 2
        A = merge_sort2(array[:mid])
        B = merge_sort2(array[mid:])

        for a in A:

            i = 0
            for b in B:

                if a >= b:
                    B.insert(i,a)
                    print(B)
                    break

                if i+1 == len(B):
                    print(B)
                    B.append(a)
                    break
                
                i += 1

        return B
```

```{python}
arr2 = [10000,6,6,6,6,6,11,6,9]
merge_sort2(arr2)
```

`[?]` What difference does `<=` or `>=` in line 17 make?  
`[>]` `a >= b` is true when the current item in array `A` is greater than or equal to `b`. If not, `b` is larger and the next items in array `B` is considered. This is repeated until one with such a condition is found. When that happens, `a` is placed to the left of `b` as defined by `help(B.insert)`. This means, that when `>=` is defined, the sort will be of descending order (from left to right), vice versa.


`[?]` Is there a difference in computation when using `<=` or `>=` generally or in specific cases?


`[?]` What doesn't `==` need to be changed at line 22?


`[?]` Why shouldn't the `B.append(a)` not be `B.insert(0,a)` for `<=` at line 17?  


#### Faster Implementation

Given that the two array that come are already sorted, the array you are sorting into should need to have the index position to reset. That is, for every item `a` added to an index position i to Array `B`, the next `a` should will have an index position of greater than or equal to `i`. This is because the next item in the array will be larger then 

```{python}
def merge_sort3(array):

    if len(array) == 1:
        return array

    else:

        mid = len(array) // 2
        A = merge_sort3(array[:mid])
        B = merge_sort3(array[mid:])
        i = 0

        for a in A:
            for j in range(i,len(B)):
                
                if a <= B[j]:
                    B.insert(j,a)
                    i = j
                    break

                if j+1 == len(B):
                    B.extend(A[i:])
                    i = j
                    break

        return B
```

```{python}
arr3 = [3,2,1,3,4,7]
merge_sort3(arr3)
```

```{python}
arr4 = [6,1006,9,0,5,1,43,2]
merge_sort3(arr4)
```

```{python}
arr5 = [9,9,9,9,9,9,9,9,0]
merge_sort3(arr5)
```

`[?]` Is there a good way to debug a recursive algorithm?

```{python}
def merge_sort4(array):

    if len(array) == 1:
        return array

    else:

        mid = len(array) // 2
        A = merge_sort3(array[:mid])
        B = merge_sort3(array[mid:])
        i = 0

        while len(A) > 0:
            a = A.pop()
            print(A,a)
            for j in range(i,len(B)):
                
                if a <= B[j]:
                    B.insert(j,a)
                    i = j
                    break

                if i+1 == len(B):
                    B.extend(A[:])
                    i = j
                    break

        return B
```

The following merge sort is broken, looking at the code what do you think is wrong with it?

```{python}
# def merge_sort(array):
  
#     if len(array) == 1:
#         return array

#     else:

#         mid = len(array) // 2
#         A = merge_sort(array[:mid])
#         B = merge_sort(array[mid:])

#         for a in A:

#             i = 0
#             for b in B:

#                 if a <= b:
#                     B.insert(i,a)
#                     break

#                 if i+1 == len(B):
#                     B.append(i,a)
#                     break


#     return B
```

__Implementation 5__

`[?]` Is and, if so, why is merge sort considered to be a divide and conquer algorithm?


`[?]` What is the sort in place variation of the merge sort algorithm?  
`[?]` How is different to just returning a new list?  
`[?]` What are costs and affordances through each one?

```{python}
def merge_sort5(list):
    """
    Sorts a list in ascending order
    Returns a new sorted list
    
    Divide: Find the midpoit of the list and divide into sublists
    Conquer: Recursively sort the sublists created in previous step
    Combine: Merge the sorted sublists created in previous step
    """
    
    # base case - stopping condition
    if len(list) <= 1:
        return list
    
    left_half, right_half = split(list)
    
    # recursive part of the function
    left = merge_sort5(left_half)
    right = merge_sort5(right_half)
    
    return merge(left,right)
```

It is interesting how the use of a higher order function can simplify and enable easier validation and optimisation. It is also easier to see the overall concept of merge sort whilst abstracting away what doesn't belong and can be optimised away.

```{python}
def split(list):
    """
    Divide the unsorted list at midpoint into sublists
    Returns two sublists - left and right
    """
    
    mid = len(list)//2
    left = list[:mid]  # start to up to but not including mid
    right = list[mid:] # len(list) = len(list[:mid]) + len(list[mid:])
    
    return left, right
```

```{python}
def merge(left,right):
    """
    Merges two lists (arrays), sorting them in the processs
    Returns a new merged list
    """
    
    l = []
    i = 0
    j = 0
    
    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            l.append(left[i])
            i += 1
            
        else:
            l.append(right[j])
            j += 1
            
    while i < len(left):
        l.append(left[i])
        i += 1
        
    while j < len(right):
        l.append(right[j])
        j += 1
        
    return l
```

```{python}
alist = [54, 62, 93, 17, 77, 31, 44, 55, 20]
l = merge_sort5(alist)
print(l)
```

```{python}
def verify_sorted(list):
    
    n = len(list)
    if n == 0 or n == 1:
        return True

    return list[0] < list[1] and verify_sorted(list[1:])
```

This function works by taking a list and comparing the first two items, and it makes an end comparison with another call to itself with a list that is one shorter from the head. 

Take a list of `[1,3,6]`, the return will the be this: `1 < 3 and 3 < 6 and True`. The last result comes from the trivial case of 
